name: manifest-release
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '!.github/**'
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git safe directory
        shell: bash
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - uses: nexient-llc/.github/actions/pre-merge@main
      - uses: nexient-llc/.github/actions/release
        with:
          mode: 'minor'
